GRANT CREATE VIEW TO SAMPLE;

SELECT * FROM SAMPLE.STUDENT;

-- AUDIT

-- SAMPLE이 HR의 EMPLOYEES의 셀렉트 할 수 있는 권한 부여
GRANT SELECT 
ON HR.EMPLOYEES 
TO SAMPLE;

-- SAMPLE이 HR의 EMPLOYEES의 셀렉트 할 수 있는 권한 철회
REVOKE SELECT 
ON HR.EMPLOYEES 
FROM SAMPLE;

-- SAMPLE CREATE SYNONYM 권한 부여
GRANT CREATE PUBLIC SYNONYM
TO SAMPLE;

GRANT DBA
TO SAMPLE;

REVOKE DBA
FROM SAMPLE;

DROP PUBLIC SYNONYM STU;
CREATE PUBLIC SYNONYM STU FOR SAMPLE.STUDENT;